export const serverl = "https://aduetechnologies.com/jinuncle/api/technician/"
export const imagebaseurl = "https://aduetechnologies.com/jinuncle/upload/"

export const Loginapi = serverl + "auth/login"
export const Otpapi = serverl + "auth/sign_up_otp_verify"
export const resendOtop = serverl + "auth/resend_otp"
export const logoutapi = serverl + "auth/logout"
export const Deleteapi = serverl + "user/delete_account"
export const getlocation = serverl + "user/get_current_location"
export const Signup = serverl + "auth/sign_up"
export const techniciantyp = serverl + "technician_type/index"
export const profile_detail = serverl + "user/profile_detail"
export const changepassword = serverl + "user/password_update"
export const helpancontact = serverl + "user/partner_enquiry"
export const historyapi = serverl + "user/user_histoey"
export const bookiglist = serverl + "user/booking_list"
export const bookingdetails = serverl + "user/booking_order_list"
export const withdrawapi = serverl + "user/withdraw_request"

